[CI] Add clang-tidy check

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -27,7 +27,7 @@ jobs:
         python-version: ${{ matrix.python-version }}
     - name: Install Dependencies
       run: |
-        sudo apt-get -y install bzip2 pbzip2 lbzip2 cppcheck # necessary for tests
+        sudo apt-get -y install bzip2 pbzip2 lbzip2 cppcheck clang-tidy # necessary for tests
         python3 -m pip install --upgrade pip
         python3 -m pip install --upgrade-strategy eager --upgrade cython twine numpy
     - name: Check committed Cython source
@@ -49,6 +49,19 @@ jobs:
         cppcheck --enable=all --std=c++17 --suppress=unusedFunction --suppress=useStlAlgorithm -I indexed_bzip2 tests/ indexed_bzip2/*hpp 2>&1 | tee cppcheck.log
         if grep -E -i '(style:|warning:|error:) .* \[[^]]*\]$' cppcheck.log; then
             echo -e '\e[31mThere were errors while running cppcheck!\e[0m'
+            exit 1
+        fi
+    - name: Run clang-tidy
+      run: |
+        mkdir -p build
+        cd build
+        cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+        make
+        cd ..
+        set -o pipefail
+        run-clang-tidy -j $( nproc ) -p build | tee clang-tidy.log
+        if grep -E -i '(style:|warning:|error:) .* \[[^]]*\]$' *.log; then
+            echo -e '\e[31mThere were errors while running clang-tidy!\e[0m'
             exit 1
         fi
     - name: Run Unit Tests
